### ISSUE TITLE
Build is failing 

### ISSUE THREAD

**Issue by vimalkansal** [grpc/grpc-go#1616]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Latest

### What version of Go are you using (`go version`)?
1.9.1

### What operating system (Linux, Windows, …) and version?
Mac

### What did you do?
Executed : go get google.golang.org/grpc

### What did you expect to see?
Expected gRPC to build and installed

### What did you see instead?
Got a compilation error 👍 
# google.golang.org/grpc/transport
google.golang.org/grpc/transport/http_util.go:486:6: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)

**Comment by dfawley** [comment]
Did you do `go get -u google.golang.org/grpc`?

**Comment by irfn** [comment]
@dfawley why was this issue closed. 
i am still seeing this issue on go1.9.2 with go-grpc 1.8.2

**Comment by menghanl** [comment]
@irfn What error did you get? If you got the same `f.fr.SetReuseFrames undefined` error, your local `http2` package is outdated. Please try to update your local packages with `go get -u golang.org/x/net/http2`. Or simply do `go get -u google.golang.org/grpc` to update all the dependencies.

**Comment by irfn** [comment]
@menghanl issue was fixed the issue by choosing different versions of net/http2 and grpc.

**Comment by FX-HAO** [comment]
Got the same issue on go 1.9. Branch `master` of `golang.org/x/net` does not fix the issue. Then I  used `elease-branch.go1.9` branch, the issue was fixed. 
```
cd $GOPATH/src/golang.org/x/net
git fetch --all
git checkout origin/release-branch.go1.9
```
I am using glide, the command is `glide get golang.org/x/net#release-branch.go1.9`.
