### ISSUE TITLE
Serve(lis net.Listener) doesn't return if listener fails

### ISSUE THREAD

**Issue by weiyougit** [grpc/grpc-go#1761]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
go1.9.2

### What operating system (Linux, Windows, …) and version?
mac 

### What did you do?
If possible, provide a recipe for reproducing the error.

the following code never exit:
```
func main() {
    grpcLis, err := net.Listen("tcp", "localhost:0")
    if err != nil {
        glog.Fatalf("gRPC listener creation failed: %s", err)
    }
    // Initialize gRPC server
    grpcServer := grpc.NewServer(grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
        MinTime: time.Minute}))

     var wg sync.WaitGroup
     wg.Add(1)
     go func() error {
         defer wg.Done()
         return grpcServer.Serve(grpcLis)
     }()
    
    // close the listener
     grpcLis.Close()
    // wait for Serve() exits, but it never did
     wg.Wait()
 }

```

### What did you expect to see?
Closing of the listener should cause Serve() function exit.
The issue is introduced in this change: https://github.com/grpc/grpc-go/pull/1745/files#diff-34c6b408d72845d076d47126c29948d1R479, line 479-484. 
According to the comment: "Block until Stop or GracefulStop is ready for us to return", so Serve function is blocked unless Stop() or GracefulStop() is called. But I think Serve() exits if listener fails(connection drops) makes more sense.

### What did you see instead?
Serve() function blocks after listener fails.

**Comment by MakMukhi** [comment]
`lis.Close()` must cause `lis.Accept()` to fail with a temporary error which causes the server to keep trying to accept.
https://github.com/grpc/grpc-go/blob/2720857d978b9873027f6d739d74794428f49c03/server.go#L504

**Comment by aaronbee** [comment]
That doesn't appear to be true:

```
func main() {
	lis, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		panic(err)
	}
	if err := lis.Close(); err != nil {
		panic(err)
	}
	_, err = lis.Accept()
	fmt.Println("Error:", err)
	fmt.Println("Temporary?", err.(interface {
		Temporary() bool
	}).Temporary())
}
```

This prints:

```
Error: accept tcp 127.0.0.1:56102: use of closed network connection
Temporary? false
```

(I would have shared on Go playground, but that doesn't allow creating a tcp socket.)

**Comment by MakMukhi** [comment]
Oh! The timing, I was just responding with the same thing. Following this realization I tried to repro your issue but was unable to. Here's my [attempt](https://github.com/grpc/grpc-go/compare/master...MakMukhi:repro_attempt?expand=1).
Can you provide a working repro?

**Comment by weiyougit** [comment]
your attempt seem to reproduce the issue, "Server exited" is never printed.

**Comment by MakMukhi** [comment]
Previously, I was doing fatalf in the server causing the program to exit before that print. I have updated the code. Did you try after the second commit? I can see "Server exited" printed:

```
mmukhi@mmukhi:~/go_code/src/google.golang.org/grpc$ go run examples/helloworld/greeter_server/main.go 
failed to serve: accept tcp [::]:50051: use of closed network connection
Server exited
```

**Comment by weiyougit** [comment]
yeah I tried the code with the second commit, and the program still hangs. Does your repo include this change? https://github.com/grpc/grpc-go/pull/1745

**Comment by MakMukhi** [comment]
My repro doesn't change any gRPC code. I've updated the helloworld example to look more like your example code:
```go
package main

import (
	"fmt"
	"log"
	"net"
	"sync"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
	"google.golang.org/grpc/reflection"
)

const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct{}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	return &pb.HelloReply{Message: "Hello " + in.Name}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		if err := s.Serve(lis); err != nil {
			fmt.Printf("failed to serve: %v\n", err)
		}
	}()
	lis.Close()
	wg.Wait()
	fmt.Println("Server exited")
}
```

Are you saying that this code on your machine doesn't print the following?

```
failed to serve: accept tcp [::]:50051: use of closed network connection
Server exited
```

**Comment by MakMukhi** [comment]
Nevermind, I my client wasn't synced to master thus #1745 wasn't taking effect. Let me retry.

**Comment by weiyougit** [comment]
sounds good, thanks for the prompt replies.

**Comment by dfawley** [comment]
Sorry for the regression.  I'll fix it and add a test case.
