### ISSUE TITLE
race between Server.Serve and Server.Stop

### ISSUE THREAD

**Issue by pohly** [grpc/grpc-go#1861]
### What version of gRPC are you using?

v1.7.5 (as in included in current Kubernetes master)

### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd64

### What operating system (Linux, Windows, …) and version?

Debian Stable

### What did you do?

When debugging a flaky test in https://github.com/kubernetes/kubernetes/issues/59488 I noticed that gRPC seems to close and thus unlink a Unix stream socket after Server.Stop() already returned. In the Kubernetes test suite that caused a test failure because the server removed the listening socket of the next test, which happened to use the same path.

I don't have a simple reproducer. Even in Kubernetes it only manifests itself when running multiple tests concurrently, i.e. the system is under load.

### What did you expect to see?

Once Server.Stop() returns, all sockets should be closed and the server no longer should do anything.

### What did you see instead?

Server.Serve() was entering line 458:
```
func (s *Server) Serve(lis net.Listener) error {
	s.mu.Lock()
	s.printf("serving")
	s.serve = true
	if s.lis == nil {
		s.mu.Unlock()
458:		lis.Close()
		return ErrServerStopped
	}
```

This is what the stacktrace in https://github.com/kubernetes/kubernetes/issues/59488#issuecomment-365291381 showed.

It's worth pointing out that the test does a `go m.server.Server()` that gets followed immediately in time by `m.server.Stop()`, so shutdown races with startup.

**Comment by dfawley** [comment]
@pohly - `Serve()` vs. `[Graceful]Stop()` issues should all be fixed by #1485 (in 1.8.0 and later releases) and/or #1745 (in 1.9.0 and later releases).  The 1.7.x branch is sufficiently old that we would rather not back-port a fix to it.  Are you able to update gRPC in Kubernetes?

**Comment by pohly** [comment]
Thanks for pointing out #1485. However, I don't think it addresses this particular problem. I had had a look at master and while the code was indeed a bit different, the underlying problems still seemed to be there. I think what happens is this:

- a Server instance with empty s.lis is created (https://github.com/grpc/grpc-go/blob/master/server.go#L334)
- a goroutine with Serve() is created, but does not run; the new listener socket is bound to the goroutine
- Stop() is called and sets s.lis to nil (https://github.com/grpc/grpc-go/blob/master/server.go#L1189)
- because s.lis was still empty, Stop() does not close any socket and returns
- the goroutine calls Serve() with  the listener socket
- Serve() detects that the server is meant to shut down and quits after closing the socket (https://github.com/grpc/grpc-go/blob/master/server.go#L474)

One can argue that Server works as intended. But then how can a user of  the Server prevent this unexpected behavior, given the current API?

I suspect that it might require an API change (something along the lines of a non-blocking Server.StartServe which takes over the socket, then starts a goroutine under the hood and returns; when Close is called, it can close that socket before returning). But before speculating about a solution, let's clarify whether we agree that there is a problem ;-}

**Comment by pohly** [comment]
On Tue, 2018-02-13 at 09:24 -0800, dfawley wrote:
> The 1.7.x branch is sufficiently old that we would rather not back-
> port a fix to it. Are you able to update gRPC in Kubernetes?

While I don't think that it would help in this case (see my other
comment), this is something that might be worthwhile by itself.

I'm new to Kubernetes, so I'll have find out what the process is for
updating components like gRPC.

**Comment by dfawley** [comment]
> One can argue that Server works as intended. But then how can a user of the Server prevent this unexpected behavior, given the current API?

It seems like you should be able to synchronize your test code such that `Serve()` is not called if `Stop()` has already been called, if you don't want the listener to be closed.  Or you could re-initialize your socket for every test case.  I'm a little confused though, because it sounds like you intend to re-use the socket in subsequent cases, but any call to `Serve()` will eventually result in the listener being closed (via `Stop()`).  I believe the listener is closed here for consistency reasons: in case the user isn't synchronized, then calling `Serve()` and `Stop()` at roughly the same time will always result in a closed listener.  Let me know if I'm misunderstanding something.

**Comment by dfawley** [comment]
OK, I understand better now.

There's an interesting comment on line 173 [here](https://golang.org/src/net/unixsock_posix.go)  (this is the `Close()` method being invoked for unix socket listeners on posix systems):
```
	// There's a race here--we can't know for
	// sure whether someone else has come along
	// and replaced our socket name already--
	// but this sequence (remove then close)
	// is at least compatible with the auto-remove
	// sequence in ListenUnix. It's only non-Go
	// programs that can mess us up.
	// Even if there are racy calls to Close, we want to unlink only for the first one.
```

So one fix is to manually call `Close` on your listener before your test case exits.  Then a late call to `Start()` with the old listener would not unlink the file again.

Another option would be to make your `Serve()` goroutine signal when it finishes (e.g. by closing a channel in your `ManagerImpl` struct after `Serve()` returns), and have your `Stop()` function wait on that after calling `m.server.Stop()`.  Then you know `Serve()` will have completed, also avoiding this problem.

Either way, you should make sure your listener is closed before you create a new one with the same filename, which is the source of your problem.

I don't think we can change grpc in a way that fixes your problem.  `Close` should always be called on every listener you create to avoid leaking resources, so if grpc didn't call `Close` on it, _you_ would still have to.  This would mean that you'd have to do the following to be correct:

```go
go func() {
  if err := m.server.Serve(s); err == ErrServerStopped {
    // grpc doesn't close our listener for us, so we have to do it ourselves.
    s.Close()
  }
}()
```

...and you'd have the same race.

**Comment by pohly** [comment]
On Tue, 2018-02-13 at 22:56 +0000, dfawley wrote:
> So one fix is to manually call Close on your listener before your
> test case exits. Then a late call to Start() with the old listener
> would not unlink the file again.

Yes, that looks like the easiest solution. I hadn't considered that
Close() can safely be called multiple times - well, for some definition
of "safely". It won't crash and for this particular case (Close() after
Stop()) one can even be certain that Serve() won't fail.

I wonder whether it is worth mentioning this in the API documentation
for Serve(). Calling it in a goroutine can't be that unusual. But I'm
new to all this, so perhaps Kubernetes really is doing something
unusual.

> Either way, you should make sure your listener is closed before you
> create a new one with the same filename, which is the source of your
> problem.
> I don't think we can change grpc in a way that fixes your problem. 
> Close should always be called on every listener you create to avoid
> leaking resources, so if grpc didn't call Close on it, you would
> still have to.

grpc is guaranteed to call Close(), eventually. But I can see how with
the current API it is the responsibility of the caller to ensure that
this has happened before proceeding.

**Comment by dfawley** [comment]
> Yes, that looks like the easiest solution.

It is easy to do, but I also have reservations about leaving rogue goroutines hanging around after a test case finishes.  You may want to check out our [`leakcheck` package](https://godoc.org/google.golang.org/grpc/test/leakcheck), which ensures no unexpected goroutines are running before calling a test a success.  (This would also take care of this race.)

> I wonder whether it is worth mentioning this in the API documentation
> for Serve(). Calling it in a goroutine can't be that unusual.

For most tests, `Serve` needs to be called in a goroutine.  I'm not sure how we can doc this, though.  This behavior is specific to unix sockets.  The docs do indicate that `lis` is always closed.
