### ISSUE TITLE
max stream concurrency not enforced (due to duplicate CloseStream)

### ISSUE THREAD

**Issue by jgraettinger** [grpc/grpc-go#952]
We encountered this while heavily loading GCP / Bigtable, and observed frequent resets of both streams and whole transports from GFE. Instrumentation showed that more than 100 streams (maximum concurrency advertised by GFE) were being created by GRPC.

The defect appears to be in [recvResponse](https://github.com/grpc/grpc-go/blob/master/call.go#L55) and it's usage in [invoke](https://github.com/grpc/grpc-go/blob/master/call.go#L208). `recvResponse` calls CloseStream on any error, including io.EOF for which it returns `nil`. In this case, [invoke](https://github.com/grpc/grpc-go/blob/master/call.go#L225) then calls CloseStream again on the stream.

I'm unclear if it's intended that CloseStream may be called call multiple times. I'm guessing not, as tests pass if `recvResponse` is fixed to exclude io.EOF & `CloseStream` is instrumented to panic on a second call. In any case, the second call definitely shouldn't [be adding duplicate stream quota](https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L475).

**Comment by iamqizhao** [comment]
I think this has been fixed in #947. We will tag the repo next Monday.

**Comment by jgraettinger** [comment]
It's not fixed. `recvResponse` still closes the stream even if err is `io.EOF`, and then returns nil (such that `invoke` closes it again too).

**Comment by iamqizhao** [comment]
No, recvResponse does not close the stream since https://github.com/grpc/grpc-go/blob/master/call.go#L75 rewrites the returned "err".

**Comment by iamqizhao** [comment]
The deferred "err" gets "nil" in this case.

**Comment by jgraettinger** [comment]
Please try actually running the code before making assertions here. Returning `nil` is definitely not the same thing as setting `err = nil` to clear it, and the `defer` still sees `err = io.EOF`. Instrument it, run the tests, and see what you get.

**Comment by iamqizhao** [comment]
https://play.golang.org/p/Gjsh24B4AU

**Comment by jgraettinger** [comment]
I stand corrected! Agreed that #947 fixes. Apologies, it's been a day.
